version: '3.8'

services:
  controller_client:
    build: .
    privileged: true  # Required for creating a virtual controller
    restart: unless-stopped
    environment:
      - LISTEN_PORT=5555
    ports:
      - "5555:5555/udp"  # Exposes the listening port
    volumes:
      - /dev/uinput:/dev/uinput  # Required to create virtual controller input
