version: '3.8'

services:
  controller_server:
    build: .
    privileged: true  # Required for accessing controller input
    restart: unless-stopped
    environment:
      - CONTROLLER_HOST=YOUR_PUBLIC_IP_OR_DOMAIN
      - CONTROLLER_PORT=5555
    ports:
      - "5555:5555/udp"  # Exposes the port for public access
    volumes:
      - /dev/input:/dev/input  # Required to access controller events
